version: '3'
services:
  service-db:
    image: postgres:16
    container_name: service-db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5433:5432'
    networks:
      - postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    networks:
      - postgres

volumes:
  postgresdata:

networks:
  postgres:
    driver: bridge
