"""Deleted "UserWeights" table

Revision ID: 2c1c01720b32
Revises: 464048642e9e
Create Date: 2024-10-29 14:00:23.996617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1c01720b32'
down_revision: Union[str, None] = '464048642e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_weightss')
    op.add_column('user_profiles', sa.Column('purpose_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('self_assessment_lvl_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_communication_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('platforms_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('playtime_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('hours_per_week_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_days_weight', sa.Float(), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_genres', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_genres')
    op.drop_column('user_profiles', 'preferred_days_weight')
    op.drop_column('user_profiles', 'hours_per_week_weight')
    op.drop_column('user_profiles', 'playtime_weight')
    op.drop_column('user_profiles', 'platforms_weight')
    op.drop_column('user_profiles', 'preferred_communication_weight')
    op.drop_column('user_profiles', 'self_assessment_lvl_weight')
    op.drop_column('user_profiles', 'purpose_weight')
    op.create_table('user_weightss',
    sa.Column('purpose_weight', sa.FLOAT(), nullable=False),
    sa.Column('self_assessment_lvl_weight', sa.FLOAT(), nullable=False),
    sa.Column('preferred_communication_weight', sa.FLOAT(), nullable=False),
    sa.Column('platforms_weight', sa.FLOAT(), nullable=False),
    sa.Column('playtime_weight', sa.FLOAT(), nullable=False),
    sa.Column('hours_per_week_weight', sa.FLOAT(), nullable=False),
    sa.Column('preferred_days_weight', sa.FLOAT(), nullable=False),
    sa.Column('preferred_genres', sa.FLOAT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
