"""Table renamed

Revision ID: 47ee67203a3a
Revises: ea341f23d7fb
Create Date: 2024-11-08 20:02:04.560858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ee67203a3a'
down_revision: Union[str, None] = 'ea341f23d7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_platform_association',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], )
    )
    op.drop_table('user_profile_platforms_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_platforms_association',
    sa.Column('user_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], )
    )
    op.drop_table('user_profile_platform_association')
    # ### end Alembic commands ###
