"""Changed some fields

Revision ID: 622ec1c0790a
Revises: 6ec6b916be0f
Create Date: 2024-10-13 00:15:34.174752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622ec1c0790a'
down_revision: Union[str, None] = '6ec6b916be0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('users', 'dof',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'dof',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    # ### end Alembic commands ###
