"""Init

Revision ID: 6e7c1495c4f2
Revises: 
Create Date: 2024-10-29 14:08:57.318362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7c1495c4f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('purpose', sa.Enum('FUN', 'RESULT', name='purposeenum'), nullable=False),
    sa.Column('self_assessment_lvl', sa.Enum('LOW', 'MID', 'HIGH', name='selfassessmentlvlenum'), nullable=False),
    sa.Column('preferred_communication', sa.Enum('VOICE', 'TEXT', 'NO', name='communicationtypeenum'), nullable=False),
    sa.Column('purpose_weight', sa.Float(), nullable=False),
    sa.Column('self_assessment_lvl_weight', sa.Float(), nullable=False),
    sa.Column('preferred_communication_weight', sa.Float(), nullable=False),
    sa.Column('platforms_weight', sa.Float(), nullable=False),
    sa.Column('playtime_weight', sa.Float(), nullable=False),
    sa.Column('hours_per_week_weight', sa.Integer(), nullable=True),
    sa.Column('preferred_days_weight', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdayenum'), nullable=True),
    sa.Column('preferred_genres', sa.Enum('RPG', 'SHOOTER', 'MOBA', 'STRATEGY', 'HORROR', 'SIMULATOR', name='genreenum'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    sa.Column('dof', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_interactions',
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('user_1_rating', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='ratingenum'), nullable=False),
    sa.Column('user_2_rating', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='ratingenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_user_1_id'), 'user_interactions', ['user_1_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_2_id'), 'user_interactions', ['user_2_id'], unique=False)
    op.create_table('user_profile_platforms_association',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile_platforms_association')
    op.drop_index(op.f('ix_user_interactions_user_2_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_user_1_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_table('platforms')
    # ### end Alembic commands ###
