"""empty message

Revision ID: abe14fdd7f58
Revises: 28cdf0793589
Create Date: 2025-01-09 11:13:36.773560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe14fdd7f58'
down_revision: Union[str, None] = '28cdf0793589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contactss',
    sa.Column('vk', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('steam', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_infos',
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('self_assessment_lvl', sa.String(), nullable=True),
    sa.Column('preferred_communication', sa.String(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_integro_tables',
    sa.Column('steam_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_weightss',
    sa.Column('purpose_weight', sa.Float(), nullable=False),
    sa.Column('self_assessment_lvl_weight', sa.Float(), nullable=False),
    sa.Column('preferred_communication_weight', sa.Float(), nullable=False),
    sa.Column('preferred_platforms_weight', sa.Float(), nullable=False),
    sa.Column('playtime_weight', sa.Float(), nullable=False),
    sa.Column('hours_per_week_weight', sa.Float(), nullable=False),
    sa.Column('preferred_days_weight', sa.Float(), nullable=False),
    sa.Column('preferred_genres_weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'purpose_weight')
    op.drop_column('users', 'self_assessment_lvl_weight')
    op.drop_column('users', 'preferred_days_weight')
    op.drop_column('users', 'hours_per_week_weight')
    op.drop_column('users', 'hours_per_week')
    op.drop_column('users', 'preferred_communication_weight')
    op.drop_column('users', 'steam_id')
    op.drop_column('users', 'preferred_genres_weight')
    op.drop_column('users', 'playtime_weight')
    op.drop_column('users', 'purpose')
    op.drop_column('users', 'preferred_platforms_weight')
    op.drop_column('users', 'preferred_communication')
    op.drop_column('users', 'self_assessment_lvl')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('self_assessment_lvl', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('preferred_communication', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('preferred_platforms_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('purpose', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('playtime_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('preferred_genres_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('steam_id', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('preferred_communication_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('hours_per_week', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('hours_per_week_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('preferred_days_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('self_assessment_lvl_weight', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('purpose_weight', sa.FLOAT(), nullable=False))
    op.drop_table('user_weightss')
    op.drop_table('user_integro_tables')
    op.drop_table('user_infos')
    op.drop_table('user_contactss')
    # ### end Alembic commands ###
