"""empty message

Revision ID: af68ff1320c9
Revises: 79acc7c7acd9
Create Date: 2024-12-11 10:29:45.872576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af68ff1320c9'
down_revision: Union[str, None] = '79acc7c7acd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'content_type')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.BLOB(), nullable=True))
    op.add_column('users', sa.Column('content_type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
