"""ffff

Revision ID: cee4df78b125
Revises: dc29324e3b03
Create Date: 2024-11-19 21:55:08.640027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee4df78b125'
down_revision: Union[str, None] = 'dc29324e3b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'content_type')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
