"""empty message

Revision ID: d0fe957b8afa
Revises: 0cc994a372d8
Create Date: 2025-03-21 14:46:23.865469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fe957b8afa'
down_revision: Union[str, None] = '0cc994a372d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_playtimes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('playtime_hours', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_name', name='uq_user_game_playtime')
    )
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rated_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('ONE_STAR', 'TWO_STARS', 'THREE_STARS', 'FOUR_STARS', 'FIVE_STARS', name='ratingenum'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rater_id', 'rated_id', name='uq_user_rating')
    )
    op.add_column('user_infos', sa.Column('preferred_days', sa.Enum('WEEKDAYS', 'WEEKENDS', name='preferreddaysenum'), nullable=True))
    op.add_column('user_infos', sa.Column('preferred_time', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', name='preferredtimeenum'), nullable=True))
    op.drop_column('user_infos', 'hours_per_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_infos', sa.Column('hours_per_week', sa.INTEGER(), nullable=True))
    op.drop_column('user_infos', 'preferred_time')
    op.drop_column('user_infos', 'preferred_days')
    op.drop_table('user_ratings')
    op.drop_table('game_playtimes')
    # ### end Alembic commands ###
