"""empty message

Revision ID: e1085c6360fd
Revises: 1836466476ef
Create Date: 2025-01-10 16:28:40.452468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1085c6360fd'
down_revision: Union[str, None] = '1836466476ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_follow', 'user_follows', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_follow', 'user_follows', ['follower_id', 'followed_id'])
    # ### end Alembic commands ###
